#!/bin/bash
#SBATCH -p staging       # use the partition staging
#SBATCH -t 5-00:00:00    # set the wall clock time
cd /projects/0/blueactn/reanalysis/MERRA2/downloader
# redirect stdout to output.txt and error to error.txt
bash download_MERRA2.sh > output.txt 2> error.txt
