#!/usr/bin/env python

"""
Copyright Netherlands eScience Center

Function        : Calculate AMET with era1980 on pressure level without mass correction
Author          : Yang Liu
Date            : 2017.8.27
Last Update     : 2017.8.27
Description     : The code aims to calculate the atmospheric meridional energy
                  transport based on atmospheric reanalysis dataset ERA-Interim
                  from ECMWF. The calculation is based on era1980 on pressure level.
                  No mass correction is applied.

Return Value    : NetCFD4 data file
Dependencies    : os, time, numpy, netCDF4, sys, matplotlib
variables       : Absolute Temperature              T
                  Specific Humidity                 q
                  Pressure                          lnsp
                  Zonal Divergent Wind              u
                  Meridional Divergent Wind         v
                  geopotential                      z
"""
import numpy as np
import time as tttt
from netCDF4 import Dataset,num2date
import os
import platform
import sys
import logging
import matplotlib.pyplot as plt

##########################################################################
###########################   Units vacabulory   #########################
# cpT:  [J / kg K] * [K]     = [J / kg]
# Lvq:  [J / kg] * [kg / kg] = [J / kg]
# gz in [m2 / s2] = [ kg m2 / kg s2 ] = [J / kg]

# multiply by v: [J / kg] * [m / s] => [J m / kg s]
# sum over longitudes [J m / kg s] * [ m ] = [J m2 / kg s]

# integrate over pressure: dp: [Pa] = [N m-2] = [kg m2 s-2 m-2] = [kg s-2]
# [J m2 / kg s] * [Pa] = [J m2 / kg s] * [kg / s2] = [J m2 / s3]
# and factor 1/g: [J m2 / s3] * [s2 /m2] = [J / s] = [Wat]
##########################################################################

# print the system structure and the path of the kernal
print platform.architecture()
print os.path

# calculate the time for the code execution
start_time = tttt.time()

# Redirect all the console output to a file
#sys.stdout = open('F:\DataBase\ERA_Interim\console.out','w')

# logging level 'DEBUG' 'INFO' 'WARNING' 'ERROR' 'CRITICAL'
#logging.basicConfig(filename = 'F:\DataBase\ERA_Interim\history.log', filemode = 'w',level = logging.DEBUG,
#                    format = '%(asctime)s - %(name)s - %(levelname)s - %(message)s')
#logging.basicConfig(filename = '/data/Reanalysis/ERA_Interim/Subdaily/Model/history.log', filemode = 'w', level = logging.DEBUG, format = '%(asctime)s - %(name)s - %(levelname)s - %(message)s')

# define the constant:
constant ={'g' : 9.80616,      # gravititional acceleration [m / s2]
           'R' : 6371009,      # radius of the earth [m]
           'cp': 1004.64,      # heat capacity of air [J/(Kg*K)]
           'Lv': 2264670,      # Latent heat of vaporization [J/Kg]
           'R_dry' : 286.9,    # gas constant of dry air [J/(kg*K)]
           'R_vap' : 461.5,    # gas constant for water vapour [J/(kg*K)]
            }

################################   Input zone  ######################################
# specify data path
datapath = 'F:\DataBase\ERA_Interim\Subdaily'
# datapath = '/project/ERA-Interim/Subdaily/Model/'
# time of the data, which concerns with the name of input
# starting time (year)
start_year = 1980
# Ending time, if only for 1 year, then it should be the same as starting year
end_year = 1980
# specify output path for the netCDF4 file
output_path = 'F:\DataBase\ERA_Interim\Subdaily'
# benchmark datasets for basic dimensions
benchmark_path = 'F:\DataBase\ERA_Interim\Subdaily\pressure_daily_075_1980\pressure_daily_075_1980_1_z.nc'
benchmark = Dataset(benchmark_path)
####################################################################################

def var_key(datapath, year, month):
    # get the path to each datasets
    print "Start retrieving datasets"
    #logging.info("Start retrieving variables T,q,v,z for from %d (y) - %d (m)" % (year,month))
    datapath_T = datapath + os.sep + 'pressure_daily_075_%d' % (year) + os.sep + 'pressure_daily_075_%d_%d_T_q.nc' % (year,month)
    datapath_q = datapath + os.sep + 'pressure_daily_075_%d' % (year) + os.sep + 'pressure_daily_075_%d_%d_T_q.nc' % (year,month)
    datapath_u = datapath + os.sep + 'pressure_daily_075_%d' % (year) + os.sep + 'pressure_daily_075_%d_%d_u_v.nc' % (year,month)
    datapath_v = datapath + os.sep + 'pressure_daily_075_%d' % (year) + os.sep + 'pressure_daily_075_%d_%d_u_v.nc' % (year,month)
    datapath_z = datapath + os.sep + 'pressure_daily_075_%d' % (year) + os.sep + 'pressure_daily_075_%d_%d_z.nc' % (year,month)
    datapath_sp = datapath + os.sep + 'pressure_daily_075_%d' % (year) + os.sep + 'pressure_daily_075_%d_%d_sp.nc' % (year,month)
    # the options are specifically for the calculation of tendency during mass budget correction
    # for the calculation of tendency, exception should be made due to the time dependency
    if month == 1:
        # datapath of q
        datapath_q_last = datapath + os.sep + 'pressure_daily_075_%d' % (year-1) + os.sep + 'pressure_daily_075_%d_%d_T_q.nc' % (year-1,12)
        datapath_q_next = datapath + os.sep + 'pressure_daily_075_%d' % (year) + os.sep + 'pressure_daily_075_%d_%d_T_q.nc' % (year,month+1)
        # datapath of surface pressure
        datapath_sp_last = datapath + os.sep + 'pressure_daily_075_%d' % (year-1) + os.sep + 'pressure_daily_075_%d_%d_sp.nc' % (year-1,12)
        datapath_sp_next = datapath + os.sep + 'pressure_daily_075_%d' % (year) + os.sep + 'pressure_daily_075_%d_%d_sp.nc' % (year,month+1)
    elif month == 12:
        datapath_q_last = datapath +os.sep + 'pressure_daily_075_%d' % (year) + os.sep + 'pressure_daily_075_%d_%d_T_q.nc' % (year,month-1)
        datapath_q_next = datapath +os.sep + 'pressure_daily_075_%d' % (year+1) + os.sep + 'pressure_daily_075_%d_%d_T_q.nc' % (year+1,1)
        datapath_sp_last = datapath + os.sep + 'pressure_daily_075_%d' % (year) + os.sep + 'pressure_daily_075_%d_%d_sp.nc' % (year,month-1)
        datapath_sp_next = datapath + os.sep + 'pressure_daily_075_%d' % (year+1) + os.sep + 'pressure_daily_075_%d_%d_sp.nc' % (year+1,1)
    else:
        datapath_q_last = datapath +os.sep + 'pressure_daily_075_%d' % (year) + os.sep + 'pressure_daily_075_%d_%d_T_q.nc' % (year,month-1)
        datapath_q_next = datapath +os.sep + 'pressure_daily_075_%d' % (year) + os.sep + 'pressure_daily_075_%d_%d_T_q.nc' % (year,month+1)
        datapath_sp_last = datapath +os.sep + 'pressure_daily_075_%d' % (year) + os.sep + 'pressure_daily_075_%d_%d_sp.nc' % (year,month-1)
        datapath_sp_next = datapath +os.sep + 'pressure_daily_075_%d' % (year) + os.sep + 'pressure_daily_075_%d_%d_sp.nc' % (year,month+1)
    # get the variable keys
    T_key = Dataset(datapath_T)
    q_key = Dataset(datapath_q)
    u_key = Dataset(datapath_u)
    v_key = Dataset(datapath_v)
    z_key = Dataset(datapath_z)
    sp_key = Dataset(datapath_sp)
    # get the variable keys for the calculation of tendency during mass budget correction
    q_last_key = Dataset(datapath_q_last)
    q_next_key = Dataset(datapath_q_next)
    sp_last_key = Dataset(datapath_sp_last)
    sp_next_key = Dataset(datapath_sp_next)
    print "Retrieving datasets successfully!"
    #logging.info("Retrieving variables for from %d (y) - %d (m) successfully!" % (year,month))
    return T_key, q_key, u_key, v_key, z_key, sp_key, q_last_key, q_next_key, sp_last_key, sp_next_key

def mass_correction(T_key, q_key, u_key, v_key, z_key, sp_key, q_last_key, q_next_key, sp_last_key, sp_next_key):
    # extract variables
    print "Start extracting variables for mass correction."
    q = q_key.variables['q'][:]
    sp = sp_key.variables['sp'][:]
    u = u_key.variables['u'][:]
    v = v_key.variables['v'][:]
    # extract variables for the calculation of tendency
    q_last = q_last_key.variables['q'][-1,:,:,:]
    q_next = q_next_key.variables['q'][0,:,:,:]
    sp_last = sp_last_key.variables['sp'][-1,:,:]
    sp_next = sp_next_key.variables['sp'][0,:,:]
    # validate time and location info
    time = T_key.variables['time'][:]
    level = T_key.variables['level'][:]
    latitude = T_key.variables['latitude'][:]
    longitude = T_key.variables['longitude'][:]
    date = num2date(time,T_key.variables['time'].units)
    print '*******************************************************************'
    print 'The datasets contain information from %s to %s' % (date[0],date[-1])
    print 'There are %d days in this month' % (len(time)/4)
    print 'The coordinates include %d vertical levels' % (len(level))
    print 'The grid employs %d points in latitude, and %d points in longitude' % (len(latitude),len(longitude))
    print '*******************************************************************'
    print 'Extracting variables successfully!'
    logging.info("Extracting variables successfully!")

    print 'Begin the calculation of precipitable water tendency'
    # calculate pressure levels
    dp = np.zeros(level.shape)
    index_level = np.arange(len(level))
    for i in index_level:
        if i == 0:
            dp[i] = level[i]*100
        else:
            dp[i] = level[i]*100 - level[i-1]*100
    # create dp with diffrent dimensions
    dp_2D = np.repeat(dp[:,np.newaxis],len(latitude),1)
    dp_3D = np.repeat(dp_2D[:,:,np.newaxis],len(longitude),2)
    dp_4D = np.repeat(dp_3D[np.newaxis,:,:,:],len(time),0)

    # calculte the precipitable water tendency and take the vertical integral
    moisture_start = np.sum((q[0,:,:,:] * dp_3D), 0) # start of the current month
    moisture_end = np.sum((q[-1,:,:,:] * dp_3D), 0) # end of the current month
    moisture_last = np.sum((q_last * dp_3D), 0) # last day of the last month
    moisture_next = np.sum((q_next * dp_3D), 0) # first day of the next month
    # compute the moisture tendency (one day has 86400s)
    moisture_tendency = ((moisture_end + moisture_next) / 2 - (moisture_last + moisture_start) / 2) / (len(time)/4*86400) / constant['g']
    print 'The calculation of precipitable water tendency is finished !!'

    # take the mean surface pressure value
    sp_mean = np.mean(sp,0)
    print 'Begin the calculation of divergent verically integrated moisture flux.'
    # calculte the mean moisture flux for a certain month
    moisture_flux_u = u * q * dp_4D / constant['g']
    moisture_flux_v = v * q * dp_4D / constant['g']
    # take the vertical integral
    moisture_flux_u_int = np.sum(moisture_flux_u,1)
    moisture_flux_v_int = np.sum(moisture_flux_v,1)
    # calculate zonal & meridional grid size on earth
    # the earth is taken as a perfect sphere, instead of a ellopsoid
    dx = 2 * np.pi * constant['R'] * np.cos(2 * np.pi * latitude / 360) / len(longitude)
    #dx[0] = 0.0001 # adjustment in case of float point fluctuation
    #dx[-1] = 0.0001
    dy = np.pi * constant['R'] / 240
    # calculate the divergence of moisture flux
    div_moisture_flux_u = np.zeros((len(time),len(latitude),len(longitude)),dtype = float)
    div_moisture_flux_v = np.zeros((len(time),len(latitude),len(longitude)),dtype = float)
    ######################## Attnention to the coordinate and symbol #######################
    # zonal moisture flux divergence
    for i in np.arange(len(latitude)):
        for j in np.arange(len(longitude)):
            # the longitude could be from 0 to 360 or -180 to 180, but the index remains the same
            if j == 0:
                div_moisture_flux_u[:,i,j] = (moisture_flux_u_int[:,i,j+1] - moisture_flux_u_int[:,i,-1]) / (2 * dx[i])
            elif j == (len(longitude)-1) :
                div_moisture_flux_u[:,i,j] = (moisture_flux_u_int[:,i,0] - moisture_flux_u_int[:,i,j-1]) / (2 * dx[i])
            else:
                div_moisture_flux_u[:,i,j] = (moisture_flux_u_int[:,i,j+1] - moisture_flux_u_int[:,i,j-1]) / (2 * dx[i])
    # meridional moisture flux divergence
    for i in np.arange(len(latitude)):
        if i == 0:
            div_moisture_flux_v[:,i,:] = -(moisture_flux_v_int[:,i+1,:] - moisture_flux_v_int[:,i,:]) / (2 * dy)
        elif i == (len(latitude)-1):
            div_moisture_flux_v[:,i,:] = -(moisture_flux_v_int[:,i,:] - moisture_flux_v_int[:,i-1,:]) / (2 * dy)
        else:
            div_moisture_flux_v[:,i,:] = -(moisture_flux_v_int[:,i+1,:] - moisture_flux_v_int[:,i-1,:]) / (2 * dy)
    print 'The calculation of divergent verically integrated moisture flux is finished !!'
    # delete intermedium variables to save memory
    del moisture_flux_u, moisture_flux_v
    # calculate evaporation minus precipitation
    E_P = np.zeros((len(latitude),len(longitude)),dtype = float)
    E_P = moisture_tendency + np.mean(div_moisture_flux_u,0) +np.mean(div_moisture_flux_v,0)
    print '*******************************************************************'
    print "******  Computation of E-P on each grid point is finished   *******"
    print '*******************************************************************'
    logging.info("Computation of E-P on each grid point is finished!")

    print 'Begin the calculation of surface pressure tendency.'
    sp_tendency = ((sp[-1,:,:] + sp_next) / 2 - (sp_last + sp[0,:,:]) / 2 ) / (len(time)/4*86400)
    print 'The calculation of surface pressure tendency is finished !!'

    print 'Begin the calculation of divergent verically integrated mass flux.'
    # calculte the mean mass flux for a certain month
    mass_flux_u = u * dp_4D / constant['g']
    mass_flux_v = v * dp_4D / constant['g']
    # take the vertical integral
    mass_flux_u_int = np.sum(mass_flux_u,1)
    mass_flux_v_int = np.sum(mass_flux_v,1)
    # calculate the divergence of moisture flux
    div_mass_flux_u = np.zeros((len(time),len(latitude),len(longitude)),dtype = float)
    div_mass_flux_v = np.zeros((len(time),len(latitude),len(longitude)),dtype = float)
    # zonal mass flux divergence
    for i in np.arange(len(latitude)):
        for j in np.arange(len(longitude)):
            # the longitude could be from 0 to 360 or -180 to 180, but the index remains the same
            if j == 0:
                div_mass_flux_u[:,i,j] = (mass_flux_u_int[:,i,j+1] - mass_flux_u_int[:,i,-1]) / (2 * dx[i])
            elif j == (len(longitude)-1) :
                div_mass_flux_u[:,i,j] = (mass_flux_u_int[:,i,0] - mass_flux_u_int[:,i,j-1]) / (2 * dx[i])
            else:
                div_mass_flux_u[:,i,j] = (mass_flux_u_int[:,i,j+1] - mass_flux_u_int[:,i,j-1]) / (2 * dx[i])
    # meridional mass flux divergence
    for i in np.arange(len(latitude)):
        if i == 0:
            div_mass_flux_v[:,i,:] = -(mass_flux_v_int[:,i+1,:] - mass_flux_v_int[:,i,:]) / (2 * dy)
        elif i == (len(latitude)-1):
            div_mass_flux_v[:,i,:] = -(mass_flux_v_int[:,i,:] - mass_flux_v_int[:,i-1,:])/ (2 * dy)
        else:
            div_mass_flux_v[:,i,:] = -(mass_flux_v_int[:,i+1,:] - mass_flux_v_int[:,i-1,:]) / (2 * dy)
    mass_residual = np.zeros((len(latitude),len(longitude)),dtype = float)
    mass_residual = sp_tendency + constant['g'] * (np.mean(div_mass_flux_u,0) + np.mean(div_mass_flux_v,0)) - constant['g'] * E_P
    # delete intermedium variables to save memory
    del mass_flux_u, mass_flux_v
    print '*******************************************************************'
    print "*** Computation of mass residual on each grid point is finished ***"
    print '*******************************************************************'
    logging.info("Computation of mass residual on each grid point is finished!")
    print 'The calculation of divergent verically integrated mass flux is finished !!'

    print 'Begin the calculation of barotropic correction wind.'
    # calculate precipitable water
    precipitable_water = q * dp_4D / constant['g']
    # take the vertical integral
    precipitable_water_int = np.mean(np.sum(precipitable_water,1),0)
    # calculate barotropic correction wind
    uc = np.zeros((len(latitude),len(longitude)),dtype = float)
    vc = np.zeros((len(latitude),len(longitude)),dtype = float)
    vc = mass_residual * dy / (sp_mean - constant['g'] * precipitable_water_int)
    vc[0,:] = 0 # Modification at polar points
    vc[-1,:] = 0
    for i in np.arange(len(latitude)):
        uc[i,:] = mass_residual[i,:] * dx[i] / (sp_mean[i,:] - constant['g'] * precipitable_water_int[i,:])
    print '********************************************************************************'
    print "*** Computation of barotropic correction wind on each grid point is finished ***"
    print '********************************************************************************'
    logging.info("Computation of barotropic correction wind on each grid point is finished!")

    return uc, vc, dp_3D, dp_4D

def meridional_energy_transport(T_key,q_key,u_key,v_key,z_key,uc,vc):
    # extract variables
    print "Start extracting variables for the quantification of meridional energy transport."
    T = T_key.variables['t'][:]
    q = q_key.variables['q'][:]
    u = v_key.variables['u'][:]
    v = v_key.variables['v'][:]
    gz = z_key.variables['z'][:]
    # Extract dimension info
    time = v_key.variables['time'][:]
    level = v_key.variables['level'][:]
    latitude = v_key.variables['latitude'][:]
    longitude = v_key.variables['longitude'][:]
    print 'Extracting variables successfully!'
    #logging.info("Extracting variables successfully!")

    print 'Start calculating meridional energy transport on pressure level'
    # calculate each component of total energy
    # take the vertical integral
    # mass correction component
    # Internal Energy cpT
    internal_flux = constant['cp'] * v * T * dp_4D / constant['g']
    internal_flux_int = np.mean(np.sum(internal_flux,1),0)
    correction_internal_flux_int = vc * np.mean(np.sum(constant['cp'] * T * dp_4D / constant['g'],1),0)
    del internal_flux, T
    # Latent heat Lq
    latent_flux = constant['Lv'] * v * q * dp_4D / constant['g']
    latent_flux_int = np.mean(np.sum(latent_flux,1),0)
    correction_latent_flux_int = vc * np.mean(np.sum(constant['Lv'] * q* dp_4D / constant['g'],1),0)
    del latent_flux, q
    # geopotential
    geopotential_flux = v * gz * dp_4D / constant['g']
    geopotential_flux_int = np.mean(np.sum(geopotential_flux,1),0)
    correction_geopotential_flux_int = vc * np.mean(np.sum(gz * dp_4D / constant['g'],1),0)
    del geopotential_flux, gz
    # kinetic energy
    kinetic_flux = v * 1/2 *(u**2 + v**2) * dp_4D / constant['g']
    kinetic_flux_int = np.mean(np.sum(kinetic_flux,1),0)
    correction_kinetic_flux_int = vc * np.mean(np.sum(1/2 *(u**2 + v**2) * dp_4D / constant['g'],1),0)
    del kinetic_flux, u, v
    # specify matrix for integral of vertical flux
    meridional_E_internal_point = np.zeros((len(latitude),len(longitude)),dtype=float)
    meridional_E_latent_point = np.zeros((len(latitude),len(longitude)),dtype=float)
    meridional_E_geopotential_point = np.zeros((len(latitude),len(longitude)),dtype=float)
    meridional_E_kinetic_point = np.zeros((len(latitude),len(longitude)),dtype=float)
    meridional_E_point = np.zeros((len(latitude),len(longitude)),dtype=float)
    # calculate zonal & meridional grid size on earth
    # the earth is taken as a perfect sphere, instead of a ellopsoid
    dx = 2 * np.pi * constant['R'] * np.cos(2 * np.pi * latitude / 360) / len(longitude)
    dx[0] = 0
    dx[-1] = 0
    # take the vertical integral
    #!!!!!!!!!!!!!!! The unit is tera-watt (TW) !!!!!!!!!!!!!!!!!!!!!!#
    for i in np.arange(len(latitude)):
        meridional_E_internal_point[i,:] = (internal_flux_int[i,:] - correction_internal_flux_int[i,:]) * dx[i]/1e+12
        meridional_E_latent_point[i,:] = (latent_flux_int[i,:] - correction_latent_flux_int[i,:]) * dx[i]/1e+12
        meridional_E_geopotential_point[i,:] = (geopotential_flux_int[i,:] - correction_geopotential_flux_int[i,:]) * dx[i]/1e+12
        meridional_E_kinetic_point[i,:] = (kinetic_flux_int[i,:] - correction_kinetic_flux_int[i,:]) * dx[i]/1e+12
    # meridional total energy transport
    meridional_E_point = meridional_E_internal_point + meridional_E_latent_point + meridional_E_geopotential_point + meridional_E_kinetic_point
    # take the zonal integral
    meridional_E_internal = np.zeros(len(latitude),dtype=float)
    meridional_E_latent = np.zeros(len(latitude),dtype=float)
    meridional_E_geopotential = np.zeros(len(latitude),dtype=float)
    meridional_E_kinetic = np.zeros(len(latitude),dtype=float)
    # meridional total energy transport
    meridional_E = np.zeros(len(latitude),dtype=float)
    for i in np.arange(len(latitude)):
        meridional_E_internal[i] = np.sum((internal_flux_int[i,:] - correction_internal_flux_int[i,:]) * dx[i])/1e+12
        meridional_E_latent[i] = np.sum((latent_flux_int[i,:] - correction_latent_flux_int[i,:]) * dx[i])/1e+12
        meridional_E_geopotential[i] = np.sum((geopotential_flux_int[i,:] - correction_geopotential_flux_int[i,:]) * dx[i])/1e+12
        meridional_E_kinetic[i] = np.sum((kinetic_flux_int[i,:] - correction_kinetic_flux_int[i,:]) * dx[i])/1e+12
    # meridional total energy transport
    meridional_E = meridional_E_internal + meridional_E_latent + meridional_E_geopotential + meridional_E_kinetic
    print '*****************************************************************************'
    print "***Computation of meridional energy transport in the atmosphere is finished**"
    print "************         The result is in tera-watt (1E+12)          ************"
    print '*****************************************************************************'
    #logging.info("Computation of meridional energy transport on pressure level is finished!")

    return meridional_E, meridional_E_internal, meridional_E_latent, meridional_E_geopotential, meridional_E_kinetic, \
    meridional_E_point, meridional_E_internal_point, meridional_E_latent_point, meridional_E_geopotential_point, meridional_E_kinetic_point

# make plots
def visualization(E_total,E_internal,E_latent,E_geopotential,E_kinetic,output_path,year):
    print "Start making plots for the total meridional energy transport and each component."
    #logging.info("Start making plots for the total meridional energy transport and each component.")
    # calculate monthly mean of total energy transport
    # unit change from tera to peta (from 1E+12 to 1E+15)
    E_total_monthly_mean = np.mean(E_total,0)/1000
    E_internal_monthly_mean = np.mean(E_internal,0)/1000
    E_latent_monthly_mean = np.mean(E_latent,0)/1000
    E_geopotential_monthly_mean = np.mean(E_geopotential,0)/1000
    E_kinetic_monthly_mean = np.mean(E_kinetic,0)/1000
    # take latitude data from benchmark variable
    Lat = benchmark.variables['latitude'][:]
    # create a 0 line
    Reference = np.zeros(len(Lat))

    # Plot the total meridional energy transport against the latitude
    fig1 = plt.figure()
    plt.plot(Lat,E_total_monthly_mean,'b-',label='ECMWF')
    #plt.hold()
    plt.plot(Lat,Reference,'r--',label='0')
    plt.title('Total Atmospheric Meridional Energy Transport %d' % (year))
    #plt.legend()
    plt.xlabel("Laitude")
    plt.xticks(np.linspace(-90,90,13))
    plt.ylabel("Meridional Energy Transport (PW)")
    #plt.show()
    fig1.savefig(output_path + os.sep + 'pressure_daily_075_%d' % (year) + os.sep + 'Meridional_Energy_total_%d.jpg' % (year), dpi = 400)

    # Plot the meridional internal energy transport against the latitude
    fig2 = plt.figure()
    plt.plot(Lat,E_internal_monthly_mean,'b-',label='ECMWF')
    #plt.hold()
    plt.plot(Lat,Reference,'r--',label='0')
    plt.title('Atmospheric Meridional Internal Energy Transport %d' % (year))
    #plt.legend()
    plt.xlabel("Laitude")
    plt.xticks(np.linspace(-90,90,13))
    plt.ylabel("Meridional Energy Transport (PW)")
    #plt.show()
    fig2.savefig(output_path + os.sep + 'pressure_daily_075_%d' % (year) + os.sep + 'Meridional_Energy_internal_%d.jpg' % (year), dpi = 400)

    # Plot the meridional latent energy transport against the latitude
    fig3 = plt.figure()
    plt.plot(Lat,E_latent_monthly_mean,'b-',label='ECMWF')
    #plt.hold()
    plt.plot(Lat,Reference,'r--',label='0')
    plt.title('Atmospheric Meridional Latent Energy Transport %d' % (year))
    #plt.legend()
    plt.xlabel("Laitude")
    plt.xticks(np.linspace(-90,90,13))
    plt.ylabel("Meridional Energy Transport (PW)")
    #plt.show()
    fig3.savefig(output_path + os.sep + 'pressure_daily_075_%d' % (year) + os.sep + 'Meridional_Energy_latent_%d.jpg' % (year), dpi = 400)

    # Plot the meridional geopotential energy transport against the latitude
    fig4 = plt.figure()
    plt.plot(Lat,E_geopotential_monthly_mean,'b-',label='ECMWF')
    #plt.hold()
    plt.plot(Lat,Reference,'r--',label='0')
    plt.title('Atmospheric Meridional Geopotential Energy Transport %d' % (year))
    #plt.legend()
    plt.xlabel("Laitude")
    plt.xticks(np.linspace(-90,90,13))
    plt.ylabel("Meridional Energy Transport (PW)")
    #plt.show()
    fig4.savefig(output_path + os.sep + 'pressure_daily_075_%d' % (year) + os.sep + 'Meridional_Energy_geopotential_%d.jpg' % (year), dpi = 400)

    # Plot the meridional geopotential energy transport against the latitude
    fig5 = plt.figure()
    plt.plot(Lat,E_kinetic_monthly_mean,'b-',label='ECMWF')
    #plt.hold()
    plt.plot(Lat,Reference,'r--',label='0')
    plt.title('Atmospheric Meridional Kinetic Energy Transport %d' % (year))
    #plt.legend()
    plt.xlabel("Laitude")
    plt.xticks(np.linspace(-90,90,13))
    plt.ylabel("Meridional Energy Transport (PW)")
    #plt.show()
    fig5.savefig(output_path + os.sep + 'pressure_daily_075_%d' % (year) + os.sep + 'Meridional_Energy_kinetic_%d.jpg' % (year), dpi = 400)
    #logging.info("The generation of plots for the total meridional energy transport and each component is complete!")

# save output datasets
def create_netcdf_point (meridional_E_point_pool,meridional_E_internal_point_pool,meridional_E_latent_point_pool,meridional_E_geopotential_point_pool,meridional_E_kinetic_point_pool,output_path,year):
    print '*******************************************************************'
    print '*********************** create netcdf file*************************'
    print '*******************************************************************'
    #logging.info("Start creating netcdf file for total meridional energy transport and each component at each grid point.")
    # wrap the datasets into netcdf file
    # 'NETCDF3_CLASSIC', 'NETCDF3_64BIT', 'NETCDF4_CLASSIC', and 'NETCDF4'
    data_wrap = Dataset(output_path+os.sep+'pressure_daily_075_%d' % (year) + os.sep + 'pressure_daily_075_%d_E_point.nc' % (year),'w',format = 'NETCDF3_64BIT')
    # create dimensions for netcdf data
    month_wrap_dim = data_wrap.createDimension('month',Dim_month)
    lat_wrap_dim = data_wrap.createDimension('latitude',Dim_latitude)
    lon_wrap_dim = data_wrap.createDimension('longitude',Dim_longitude)
    # create coordinate variables for 3-dimensions
    month_wrap_var = data_wrap.createVariable('month',np.int32,('month',))
    lat_wrap_var = data_wrap.createVariable('latitude',np.float32,('latitude',))
    lon_wrap_var = data_wrap.createVariable('longitude',np.float32,('longitude',))

    E_total_wrap_var = data_wrap.createVariable('E',np.float64,('month','latitude','longitude'))
    E_internal_wrap_var = data_wrap.createVariable('E_cpT',np.float64,('month','latitude','longitude'))
    E_latent_wrap_var = data_wrap.createVariable('E_Lvq',np.float64,('month','latitude','longitude'))
    E_geopotential_wrap_var = data_wrap.createVariable('E_gz',np.float64,('month','latitude','longitude'))
    E_kinetic_wrap_var = data_wrap.createVariable('E_u2',np.float64,('month','latitude','longitude'))
    # global attributes
    data_wrap.description = 'Monthly mean meridional energy transport and each component at each grid point'
    # variable attributes
    lat_wrap_var.units = 'degree_north'
    lon_wrap_var.units = 'degree_east'
    E_total_wrap_var.units = 'tera watt'
    E_internal_wrap_var.units = 'tera watt'
    E_latent_wrap_var.units = 'tera watt'
    E_geopotential_wrap_var.units = 'tera watt'
    E_kinetic_wrap_var.units = 'tera watt'

    E_total_wrap_var.long_name = 'atmospheric meridional energy transport'
    E_internal_wrap_var.long_name = 'atmospheric meridional internal energy transport'
    E_latent_wrap_var.long_name = 'atmospheric meridional latent heat transport'
    E_geopotential_wrap_var.long_name = 'atmospheric meridional geopotential transport'
    E_kinetic_wrap_var.long_name = 'atmospheric meridional kinetic transport'
    # writing data
    lat_wrap_var[:] = benchmark.variables['latitude'][:]
    lon_wrap_var[:] = benchmark.variables['longitude'][:]
    month_wrap_var[:] = index_month
    E_total_wrap_var[:] = meridional_E_point_pool
    E_internal_wrap_var[:] = meridional_E_internal_point_pool
    E_latent_wrap_var[:] = meridional_E_latent_point_pool
    E_geopotential_wrap_var[:] = meridional_E_geopotential_point_pool
    E_kinetic_wrap_var[:] = meridional_E_kinetic_point_pool
    # close the file
    data_wrap.close()
    print "Create netcdf file successfully"
    logging.info("The generation of netcdf files for the total meridional energy transport and each component on each grid point is complete!!")

# save output datasets
def create_netcdf_zonal_int (meridional_E_pool,meridional_E_internal_pool,meridional_E_latent_pool,meridional_E_geopotential_pool, meridional_E_kinetic_pool,output_path,year):
    print '*******************************************************************'
    print '*********************** create netcdf file*************************'
    print '*******************************************************************'
    logging.info("Start creating netcdf files for the zonal integral of total meridional energy transport and each component.")
    # wrap the datasets into netcdf file
    # 'NETCDF3_CLASSIC', 'NETCDF3_64BIT', 'NETCDF4_CLASSIC', and 'NETCDF4'
    data_wrap = Dataset(output_path+os.sep+'pressure_daily_075_%d' % (year) + os.sep + 'pressure_daily_075_%d_E_zonal_int.nc' % (year),'w',format = 'NETCDF3_64BIT')
    # create dimensions for netcdf data
    month_wrap_dim = data_wrap.createDimension('month',Dim_month)
    lat_wrap_dim = data_wrap.createDimension('latitude',Dim_latitude)
    # create coordinate variables for 3-dimensions
    month_wrap_var = data_wrap.createVariable('month',np.int32,('month',))
    lat_wrap_var = data_wrap.createVariable('latitude',np.float32,('latitude',))
    # create the actual 3-d variable
    E_total_wrap_var = data_wrap.createVariable('E',np.float64,('month','latitude'))
    E_internal_wrap_var = data_wrap.createVariable('E_cpT',np.float64,('month','latitude'))
    E_latent_wrap_var = data_wrap.createVariable('E_Lvq',np.float64,('month','latitude'))
    E_geopotential_wrap_var = data_wrap.createVariable('E_gz',np.float64,('month','latitude'))
    E_kinetic_wrap_var = data_wrap.createVariable('E_u2',np.float64,('month','latitude'))
    # global attributes
    data_wrap.description = 'Monthly mean zonal integral of meridional energy transport and each component'
    # variable attributes
    lat_wrap_var.units = 'degree_north'
    E_total_wrap_var.units = 'tera watt'
    E_internal_wrap_var.units = 'tera watt'
    E_latent_wrap_var.units = 'tera watt'
    E_geopotential_wrap_var.units = 'tera watt'
    E_kinetic_wrap_var.units = 'tera watt'

    E_total_wrap_var.long_name = 'atmospheric meridional energy transport'
    E_internal_wrap_var.long_name = 'atmospheric meridional internal energy transport'
    E_latent_wrap_var.long_name = 'atmospheric meridional latent heat transport'
    E_geopotential_wrap_var.long_name = 'atmospheric meridional geopotential transport'
    E_kinetic_wrap_var.long_name = 'atmospheric meridional kinetic transport'
    # writing data
    lat_wrap_var[:] = benchmark.variables['latitude'][:]
    month_wrap_var[:] = index_month
    E_total_wrap_var[:] = meridional_E_pool
    E_internal_wrap_var[:] = meridional_E_internal_pool
    E_latent_wrap_var[:] = meridional_E_latent_pool
    E_geopotential_wrap_var[:] = meridional_E_geopotential_pool
    E_kinetic_wrap_var[:] = meridional_E_kinetic_pool
    # close the file
    data_wrap.close()
    print "Create netcdf file successfully"
    #logging.info("The generation of netcdf files for the zonal integral of total meridional energy transport and each component is complete!!")

if __name__=="__main__":
    # create the month index
    period = np.arange(start_year,end_year+1,1)
    index_month = np.arange(1,13,1)
    # create dimensions for saving data
    #Dim_level = len(benchmark.variables['level'][:])
    Dim_latitude = len(benchmark.variables['latitude'][:])
    Dim_longitude = len(benchmark.variables['longitude'][:])
    Dim_month = len(index_month)
    #Dim_year = len(period)
    # data pool for zonal integral
    meridional_E_pool = np.zeros((Dim_month,Dim_latitude),dtype = float)
    meridional_E_internal_pool = np.zeros((Dim_month,Dim_latitude),dtype = float)
    meridional_E_latent_pool = np.zeros((Dim_month,Dim_latitude),dtype = float)
    meridional_E_geopotential_pool = np.zeros((Dim_month,Dim_latitude),dtype = float)
    meridional_E_kinetic_pool = np.zeros((Dim_month,Dim_latitude),dtype = float)
    # data pool for grid point values
    meridional_E_point_pool = np.zeros((Dim_month,Dim_latitude,Dim_longitude),dtype = float)
    meridional_E_internal_point_pool = np.zeros((Dim_month,Dim_latitude,Dim_longitude),dtype = float)
    meridional_E_latent_point_pool = np.zeros((Dim_month,Dim_latitude,Dim_longitude),dtype = float)
    meridional_E_geopotential_point_pool = np.zeros((Dim_month,Dim_latitude,Dim_longitude),dtype = float)
    meridional_E_kinetic_point_pool = np.zeros((Dim_month,Dim_latitude,Dim_longitude),dtype = float)
    # loop for calculation
    for i in period:
        for j in index_month:
            # get the key of each variable
            T_key, q_key, u_key, v_key, z_key, sp_key, q_last_key, q_next_key, sp_last_key, sp_next_key = var_key(datapath,i,j)
            # calculate barotropic correction wind based on mass budget correction
            uc, vc, dp_3D, dp_4D = mass_correction(T_key, q_key, u_key, v_key, z_key, sp_key, q_last_key, q_next_key, sp_last_key, sp_next_key)
            # calculate AMET and each component
            meridional_E, meridional_E_internal, meridional_E_latent, meridional_E_geopotential, meridional_E_kinetic,meridional_E_point, meridional_E_internal_point, meridional_E_latent_point, meridional_E_geopotential_point, meridional_E_kinetic_point = meridional_energy_transport(T_key,q_key,u_key,v_key,z_key, uc, vc)
            # save the total meridional energy and each component to the data pool
            meridional_E_pool[j-1,:] = meridional_E
            meridional_E_internal_pool[j-1,:] = meridional_E_internal
            meridional_E_latent_pool[j-1,:] = meridional_E_latent
            meridional_E_geopotential_pool[j-1,:] = meridional_E_geopotential
            meridional_E_kinetic_pool[j-1,:] = meridional_E_kinetic
            # save the meridional energy on each grid point to the data pool
            meridional_E_point_pool[j-1,:,:] = meridional_E_point
            meridional_E_internal_point_pool[j-1,:,:] = meridional_E_internal_point
            meridional_E_latent_point_pool[j-1,:,:] = meridional_E_latent_point
            meridional_E_geopotential_point_pool[j-1,:,:] = meridional_E_geopotential_point
            meridional_E_kinetic_point_pool[j-1,:,:] = meridional_E_kinetic_point
        # make plots for monthly means
        visualization(meridional_E_pool,meridional_E_internal_pool,meridional_E_latent_pool,meridional_E_geopotential_pool,meridional_E_kinetic_pool,output_path,i)
        # save data as netcdf file
        create_netcdf_zonal_int(meridional_E_pool,meridional_E_internal_pool,meridional_E_latent_pool,meridional_E_geopotential_pool,meridional_E_kinetic_pool,output_path,i)
        create_netcdf_point(meridional_E_point_pool,meridional_E_internal_point_pool,meridional_E_latent_point_pool,meridional_E_geopotential_point_pool,meridional_E_kinetic_point_pool,output_path,i)
    print 'Computation of meridional energy transport on pressure level for ERA-Interim is complete!!!'
    print 'The output is in sleep, safe and sound!!!'

print ("--- %s minutes ---" % ((tttt.time() - start_time)/60))
